# EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/processed/eco_bici_limpio.csv')

In [3]:
df.shape

(22907263, 10)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22907263 entries, 0 to 22907262
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   genero_usuario         object
 1   edad_usuario           float64
 2   bici                   int64
 3   ciclo_estacion_retiro  int64
 4   fecha_retiro           object
 5   hora_retiro            object
 6   ciclo_estacionarribo   int64
 7   fecha_arribo           object
 8   hora_arribo            object
 9   fecha                  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1.7+ GB

In [5]:
df.describe()

       edad_usuario          bici  ciclo_estacion_retiro  ciclo_estacionarribo
count  2.290726e+07  2.290726e+07           2.290726e+07          2.290726e+07
mean   3.424789e+01  5.465407e+06           2.952827e+02          2.919970e+02
std    9.827688e+00  2.023987e+06           2.120570e+02          2.134173e+02
min    1.600000e+01  2.000461e+06           1.000000e+00          1.000000e+00
25%    2.700000e+01  3.733581e+06           1.060000e+02          9.700000e+01
50%    3.200000e+01  5.472956e+06           2.550000e+02          2.490000e+02
75%    3.900000e+01  7.213606e+06           4.890000e+02          4.900000e+02
max    1.430000e+02  8.999708e+06           1.000000e+03          1.000000e+03

In [9]:
df.head(3)

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha,hora
0,M,26.0,5180930,568,31/12/2024,1900-01-01 23:57:02,572,01/01/2025,1900-01-01 00:00:03,-1 days +00:03:01,+00:03:01
1,F,54.0,3653953,283,31/12/2024,1900-01-01 23:51:40,596,01/01/2025,1900-01-01 00:00:41,-1 days +00:09:01,+00:09:01
2,M,38.0,7511322,34,31/12/2024,1900-01-01 23:48:36,64,01/01/2025,1900-01-01 00:00:59,-1 days +00:12:23,+00:12:23

In [17]:
#separa dia y hora
df['hora'] = df['fecha'].str.split(' ').str[-1]

AttributeError: Can only use .str accessor with string values!

In [8]:
df['fecha'] = pd.to_timedelta(df['fecha'])

In [10]:
#df['tiempo_hora'] = df['fecha'].dt.strftime('%H:%M:%S')
df['horas_sin_dias'] = (df['fecha'] % pd.Timedelta(days=1)).dt.total_seconds() / 3600

In [11]:
df['minutos'] = df['horas_sin_dias'] * 60

### Analizar por qué hay registros mayores a 50 minutos y

In [21]:
df_mayor_50 = df[df['minutos'] >= 50]

numero = (df['minutos'] >= 50).sum()



print(f'El Numero de personas que usaron la bicicleta por mas de 50 minutos es: {numero}')

El Numero de personas que usaron la bicicleta por mas de 50 minutos es: 219781

### Determinar si son errores de sistema o usuarios que excedieron el tiempo permitido.

In [23]:
df_mayor_50.describe()

,edad_usuario,bici,ciclo_estacion_retiro,ciclo_estacionarribo,fecha,horas_sin_dias,minutos
count,219781.000000,2.197810e+05,219781.000000,219781.000000,219781,219781.000000,219781.000000
mean,34.224228,5.467885e+06,242.188670,251.590556,0 days 00:50:09.177381120,1.381444,82.886632
std,10.414637,2.024494e+06,210.103711,218.430054,0 days 02:59:11.192571833,1.481858,88.911504
min,16.000000,2.000461e+06,1.000000,1.000000,-1 days +00:50:00,0.833333,50.000000
25%,27.000000,3.732849e+06,59.000000,61.000000,0 days 00:53:49,0.904444,54.266667
50%,32.000000,5.478359e+06,188.000000,194.000000,0 days 01:01:15,1.034444,62.066667
75%,39.000000,7.216393e+06,404.000000,432.000000,0 days 01:17:29,1.317778,79.066667
max,143.000000,8.999708e+06,1000.000000,1000.000000,0 days 20:51:24,23.986389,1439.183333

In [31]:
#tiempos demasiado altos
muyAltos =df[df['minutos'] > 300]
muyAltos

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha,hora,horas_sin_dias,minutos
336,M,25.0,4309837,119,31/12/2024,1900-01-01 23:00:45,16,01/01/2025,1900-01-01 04:13:21,-1 days +05:12:36,+05:12:36,5.210000,312.600000
499,M,44.0,3021250,555,01/01/2025,1900-01-01 00:05:41,555,01/01/2025,1900-01-01 06:46:28,0 days 06:40:47,06:40:47,6.679722,400.783333
1222,M,32.0,2330363,27,31/12/2024,1900-01-01 19:40:18,28,01/01/2025,1900-01-01 09:45:23,-1 days +14:05:05,+14:05:05,14.084722,845.083333
1461,M,27.0,2670966,54,31/12/2024,1900-01-01 23:06:23,60,01/01/2025,1900-01-01 10:17:34,-1 days +11:11:11,+11:11:11,11.186389,671.183333
2546,M,52.0,8381493,231,31/12/2024,1900-01-01 13:36:25,233,01/01/2025,1900-01-01 12:00:32,-1 days +22:24:07,+22:24:07,22.401944,1344.116667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22891214,M,28.0,2412724,212,31/03/2026,1900-01-01 10:03:32,36,31/03/2026,1900-01-01 17:47:14,0 days 07:43:42,07:43:42,7.728333,463.700000
22891341,F,20.0,8316747,150,31/03/2026,1900-01-01 12:16:23,568,31/03/2026,1900-01-01 17:49:02,0 days 05:32:39,05:32:39,5.544167,332.650000
22895293,F,30.0,3093408,215,29/03/2026,1900-01-01 08:59:12,342,31/03/2026,1900-01-01 18:40:59,0 days 09:41:47,09:41:47,9.696389,581.783333
22905669,M,64.0,6814958,574,31/03/2026,1900-01-01 16:10:39,574,31/03/2026,1900-01-01 22:22:43,0 days 06:12:04,06:12:04,6.201111,372.066667
22906562,M,24.0,7586548,635,31/03/2026,1900-01-01 16:53:46,631,31/03/2026,1900-01-01 23:04:49,0 days 06:11:03,06:11:03,6.184167,371.050000

In [32]:
len(muyAltos)

4094

In [34]:
# valores repetidos sospechosos
df_mayor_50['minutos'].value_counts().head(10)

minutos
50.116667    295
50.100000    294
50.033333    289
50.433333    287
50.266667    286
50.216667    286
50.016667    286
50.066667    275
50.616667    274
50.333333    273
Name: count, dtype: int64

In [35]:
#valores negativos o cero

df[df['minutos']<= 0]

Empty DataFrame
Columns: [genero_usuario, edad_usuario, bici, ciclo_estacion_retiro, fecha_retiro, hora_retiro, ciclo_estacionarribo, fecha_arribo, hora_arribo, fecha, hora, horas_sin_dias, minutos]
Index: []

In [36]:
df['minutos'].describe()

count    2.290726e+07
mean     1.511678e+01
std      1.469447e+01
min      1.666667e-01
25%      7.033333e+00
50%      1.175000e+01
75%      1.980000e+01
max      1.439183e+03
Name: minutos, dtype: float64

In [41]:
#Detectar outliers
q1 = df['minutos'].quantile(0.25)
q3 = df['minutos'].quantile(0.75)
iqr = q3 - q1

limite_superior = q3 + 1.5 * iqr

outliers = df[df['minutos'] > limite_superior]

In [40]:
# usuarios > 50 min
df_mayor_50 = df[df['minutos'] > 50]

# posibles errores extremos
df_error = df[df['minutos'] > 300]

# porcentaje
porcentaje = len(df_mayor_50) / len(df) * 100

print(f"Usuarios > 50 min: {len(df_mayor_50)} ({porcentaje:.2f}%)")
print(f"Posibles errores (>300 min): {len(df_error)}")

Usuarios > 50 min: 219521 (0.96%)
Posibles errores (>300 min): 4094

## Determinar la duración media por trayecto para establecer un "estándar" de uso.

In [45]:
mediaDuracion = df['minutos'].mean()
print(f'La duracion media de los viajes es: {mediaDuracion:.2f} minutos')

La duracion media de los viajes es: 15.12 minutos

In [51]:
cambioDia = (df['fecha'] < pd.Timedelta(0)).sum()

print(f'El Numero de viajes hace de cambio de dia es: {cambioDia}')

El Numero de viajes hace de cambio de dia es: 59573

# 2. Análisis de Demanda y Flujo

### Determinar cuáles son las estaciones de arribo (ciclo_estacionarribo) con mayor volumen de tráfico.

In [66]:
top_estaciones = df['ciclo_estacionarribo'].value_counts().reset_index()
top_estaciones.columns = ['estacion', 'total']

In [69]:
#Las 100 estaciones con mas arribos
top_estaciones.head(100)

    estacion   total
0        548  164475
1         14  144549
2         27  136360
3         64  134534
4         43  106526
..       ...     ...
95       128   54856
96       123   54641
97       151   54065
98       190   53613
99       164   53511

[100 rows x 2 columns]

In [56]:
df.head(3)

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha,hora,horas_sin_dias,minutos
0,M,26.0,5180930,568,31/12/2024,1900-01-01 23:57:02,572,01/01/2025,1900-01-01 00:00:03,-1 days +00:03:01,+00:03:01,0.050278,3.016667
1,F,54.0,3653953,283,31/12/2024,1900-01-01 23:51:40,596,01/01/2025,1900-01-01 00:00:41,-1 days +00:09:01,+00:09:01,0.150278,9.016667
2,M,38.0,7511322,34,31/12/2024,1900-01-01 23:48:36,64,01/01/2025,1900-01-01 00:00:59,-1 days +00:12:23,+00:12:23,0.206389,12.383333