# EDA

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df = pd.read_csv('../data/processed/eco_bici_limpio.csv')

In [5]:
df.shape

(22907263, 10)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22907263 entries, 0 to 22907262
Data columns (total 10 columns):
 #   Column                 Dtype
---  ------                 -----
 0   genero_usuario         object
 1   edad_usuario           float64
 2   bici                   int64
 3   ciclo_estacion_retiro  int64
 4   fecha_retiro           object
 5   hora_retiro            object
 6   ciclo_estacionarribo   int64
 7   fecha_arribo           object
 8   hora_arribo            object
 9   fecha                  object
dtypes: float64(1), int64(3), object(6)
memory usage: 1.7+ GB

In [7]:
df.describe()

       edad_usuario          bici  ciclo_estacion_retiro  ciclo_estacionarribo
count  2.290726e+07  2.290726e+07           2.290726e+07          2.290726e+07
mean   3.424789e+01  5.465407e+06           2.952827e+02          2.919970e+02
std    9.827688e+00  2.023987e+06           2.120570e+02          2.134173e+02
min    1.600000e+01  2.000461e+06           1.000000e+00          1.000000e+00
25%    2.700000e+01  3.733581e+06           1.060000e+02          9.700000e+01
50%    3.200000e+01  5.472956e+06           2.550000e+02          2.490000e+02
75%    3.900000e+01  7.213606e+06           4.890000e+02          4.900000e+02
max    1.430000e+02  8.999708e+06           1.000000e+03          1.000000e+03

In [64]:
df.tail(3)

,genero_usuario,edad_usuario,bici,ciclo_estacion_retiro,fecha_retiro,hora_retiro,ciclo_estacionarribo,fecha_arribo,hora_arribo,fecha,hora,horas_sin_dias,minutos,uso_60
22907260,M,32.0,4106449,1,31/03/2026,1900-01-01 23:40:14,549,31/03/2026,1900-01-01 23:59:25,0 days 00:19:11,00:19:11,0.319722,19.183333,NaN
22907261,M,43.0,5261508,231,31/03/2026,1900-01-01 23:41:27,34,31/03/2026,1900-01-01 23:59:31,0 days 00:18:04,00:18:04,0.301111,18.066667,NaN
22907262,M,29.0,2794444,641,31/03/2026,1900-01-01 23:41:13,668,31/03/2026,1900-01-01 23:59:50,0 days 00:18:37,00:18:37,0.310278,18.616667,NaN

In [27]:
#separa dia y hora
df['hora'] = df['fecha'].str.split(' ').str[-1]

In [30]:
df['fecha'] = pd.to_timedelta(df['fecha'])

In [38]:
#df['tiempo_hora'] = df['fecha'].dt.strftime('%H:%M:%S')
df['horas_sin_dias'] = (df['fecha'] % pd.Timedelta(days=1)).dt.total_seconds() / 3600

In [43]:
df['minutos'] = df['horas_sin_dias'] * 60

In [87]:
numero = (df['minutos'] >= 50).sum()

print(f'El Numero de personas que usaron la bicicleta por mas de 50 minutos es: {numero}')

El Numero de personas que usaron la bicicleta por mas de 50 minutos es: 274315

In [92]:
#Calcular el tiempo promedio de viaje
vieaje_promedio = df['minutos'].mean()

print(f'El tiempo promedio de viaje es: {vieaje_promedio:.2f} minutos')

El tiempo promedio de viaje es: 18.58 minutos

In [69]:
df.columns

Index(['genero_usuario', 'edad_usuario', 'bici', 'ciclo_estacion_retiro',
       'fecha_retiro', 'hora_retiro', 'ciclo_estacionarribo', 'fecha_arribo',
       'hora_arribo', 'fecha', 'hora', 'horas_sin_dias', 'minutos', 'uso_60'],
      dtype='object')